### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by sonydogg** [hjelev/rpi-mqtt-monitor#11]
Tried both manually installing and using the script. Fails to run with a divide by zero error. Thoughts?

awk: cmd. line:1: (FILENAME=- FNR=3) fatal: division by zero attempted
Traceback (most recent call last):
  File "/home/*/rpi-cpu2mqtt.py", line 249, in <module>
    swap = check_swap()
  File "/home/*/rpi-cpu2mqtt.py", line 51, in check_swap
    swap = round(float(swap.decode("utf-8").replace(",", ".")), 1)
ValueError: could not convert string to float: ''

**Comment by hjelev** [comment]
Hi,
What hardware and OS are you using?

If you change this line:

File "/home//rpi-cpu2mqtt.py", line 249, in
swap = check_swap()

to 
swap = 0

You should get the script working w/o the swap usage part, it will always show 0

This swap function is executing this via shell:
free -t | awk 'NR == 3 {print $3/$2*100}'

reading the output and converting it from string to float in order to round it up.
If you are not happy to disable swap, provide the output of this shell command and I'll be able to troubleshoot further.
